src/cart/urls.py
from django.urls import path
app_name="cart"
from . import views

urlpatterns = [
    path('add/', views.AddBookToCart.as_view(),name='add'),
    path('mycart/', views.CartDetail.as_view(),name='my'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(),name='delete'),

]

src/order/urls.py
from django.urls import path
app_name="order"
from . import views

urlpatterns = [
    path('create/', views.CreateOrder.as_view(),name='create'),
    path('update/<int:pk>', views.OrderUpdate.as_view(),name='update'),
    # path('delete/<int:pk>', views.BookInCartDelete.as_view(),name='delete'),

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path , include
from test_hello_word.views import test_form,test_pk,test_created,test,Test_B_V,Genre_Create,Genre_Update,Genre_List,Genre_Delete,Genre_DetaleView
from books.views import BooksCreate,BooksDetail,BooksUpdate,BooksDelete,BooksList
from home_page.views import Home_page
from django.conf import settings
from django.conf.urls.static import static
from books.auth_view import Mylogin,Mylogout,MyPasswordChange
from profiles import urls
from order import urls
from cart import urls
# from phones import 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home_page.as_view(),name='home_page'),
    path('catalogs/',include('test_hello_word.urls', namespace="CRUD_genre")),
    path('books/',include('books.urls', namespace="CRUDL_books")),
    path('login/',Mylogin.as_view(), name='login'),
    path('logout/',Mylogout.as_view(), name='logout'),
    path('change-password/',MyPasswordChange.as_view(), name='change-password'),
    path('profiles/',include('profiles.urls', namespace="CRUDL_profiles")),
    path('cart/',include('cart.urls', namespace="cart")),
    path('s-admin/',include('s_admin.urls', namespace="s-admin")),
    path('order/',include('order.urls', namespace="order"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#конструкция +static  специально для режими разработке, в проде эту строку нужно удалить

src/s_admin/urls.py
from django.urls import path
app_name="s-admin"
from . import views

urlpatterns = [
    path('', views.S_Admin.as_view(),name='index'),
    path('customers', views.CustomersList.as_view(),name='customers'),
    path('customers/update/<int:pk>', views.CustomersUpdate.as_view(),name='update'),
    path('customers/detail/<int:pk>', views.CustomersDetail.as_view(),name='detail'),

    path('books', views.SAdminBooksList.as_view(),name='books'),
    path('books/create', views.SAdminBooksCreate.as_view(),name='books_create'),
    path('books/update/<int:pk>', views.SAdminBooksUpdate.as_view(),name='books_update'),
    path('books/detail/<int:pk>', views.SAdminBooksDetail.as_view(),name='books_detail'),
    path('books/delete/<int:pk>', views.SAdminBooksDelete.as_view(),name='books_delete'),

    path('genre', views.SAdminGenreList.as_view(),name='genre'),
    path('genre/create', views.SAdminGenreCreate.as_view(),name='genre_create'),
    path('genre/update/<int:pk>', views.SAdminGenreUpdate.as_view(),name='genre_update'),
    path('genre/detail/<int:pk>', views.SAdminGenreDetail.as_view(),name='genre_detail'),
    path('genre/delete/<int:pk>', views.SAdminGenreDelete.as_view(),name='genre_delete'),
    
    path('author', views.SAdminAuthorList.as_view(),name='author'),
    path('author/create', views.SAdminAuthorCreate.as_view(),name='author_create'),
    path('author/update/<int:pk>', views.SAdminAuthorUpdate.as_view(),name='author_update'),
    path('author/detail/<int:pk>', views.SAdminAuthorDetail.as_view(),name='author_detail'),
    path('author/delete/<int:pk>', views.SAdminAuthorDelete.as_view(),name='author_delete'),

    path('cart', views.SAdminCartList.as_view(),name='cart'),
    path('cart/update/<int:pk>', views.SAdminCartUpdate.as_view(),name='cart_update'),
    path('cart/detail/<int:pk>', views.SAdminCartDetail.as_view(),name='cart_detail'),
    path('cart/delete/<int:pk>', views.SAdminCartDelete.as_view(),name='cart_delete'),

    path('publisher', views.SAdminPublisherList.as_view(),name='publisher'),
    path('publisher/create', views.SAdminPublisherCreate.as_view(),name='publisher_create'),
    path('publisher/update/<int:pk>', views.SAdminPublisherUpdate.as_view(),name='publisher_update'),
    path('publisher/delete/<int:pk>', views.SAdminPublisherDelete.as_view(),name='publisher_delete'),

    path('series', views.SAdminSeriesList.as_view(),name='series'),
    path('series/create', views.SAdminSeriesCreate.as_view(),name='series_create'),
    path('series/update/<int:pk>', views.SAdminSeriesUpdate.as_view(),name='series_update'),
    path('series/delete/<int:pk>', views.SAdminSeriesDelete.as_view(),name='series_delete'),

    path('order', views.SAdminOrderList.as_view(),name='order'),
    #доделать
    # path('order/detail/<int:pk>', views.SAdminCartDetail.as_view(),name='order_detail'),
    path('order/update/<int:pk>', views.SAdminOrderUpdate.as_view(),name='order_update'),
    path('order/delete/<int:pk>', views.SAdminSeriesDelete.as_view(),name='orders_delete'),
]

src/order/models.py
from django.db import models
from cart.models import Cart
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.

class Order(models.Model):
    cart=models.OneToOneField(
        Cart,
        on_delete=models.PROTECT,
    )
    status=models.BooleanField(
        verbose_name="Отменить заказ",
        default=False
    )
    status2 = models.CharField(
        verbose_name='Статус заказа',
        choices=(('В обработке', 'В обработке'),('Доставка', 'Доставка'), ('Отменен', 'Отменен'),('Выполнен', 'Выполнен')),
        max_length= 100,
        default = 'В обработке',
    )

    delivery_address=models.TextField(
        verbose_name="Адрес доставки",
    )
    contact_phone=PhoneNumberField(
        null=True,
        verbose_name="Телефон",     
    )
    create=models.DateField(
        verbose_name="Дата cоздания",
        auto_now=False,
        auto_now_add=True
    )
    update=models.DateField(
        verbose_name="Дата последнего изменения",
        auto_now=True,
        auto_now_add=False
    )
    comment=models.TextField(
        verbose_name="Комментарий к заказу",
        blank=True,
        null=True
    )
    def __str__(self):
        return f"Заказ #{self.pk}"

src/order/views.py
from django.shortcuts import render
from django.views.generic import CreateView,DetailView,UpdateView,DeleteView,ListView,FormView
from profiles.models import Profile
from books.models import Books
from cart.models import Cart,BookInCart
from .models import Order
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from datetime import datetime
# Create your views here.

# Create your views here.

class CreateOrder(SuccessMessageMixin,UpdateView):
    model=Order
    context_object_name='order'
    template_name="order/create.html"
    fields=('delivery_address','contact_phone','comment')


    def get_object(self, queryset=None):
        #набросок для заполнения данными из юзера поля телефон и  адрес 
        try:
            user=self.request.user
            print(user)
            prof_user=Profile.objects.get(username=user)
        except Profile.DoesNotExist:
            prof_user=None
        # print(prof_user.is_anonymous)
        if prof_user == None:
            print("prof_user is none",prof_user)
            delivery_address1="Please fill in"
            contact_phone="Please fill in"
        else:
            delivery_address1=prof_user.address_1
            contact_phone=prof_user.phone

        #получаю корзину
        cart_pk=self.request.session.get('cart_pk')
        print('cart_pk:',cart_pk)

        cart=Cart.objects.get(pk=cart_pk)

        order_pk=cart.pk
   

        obj,created=self.model.objects.get_or_create(
            pk=order_pk,
            defaults={
                'cart' :cart,
                'status': False,
                'delivery_address': delivery_address1,
                'contact_phone': contact_phone,  
            }
            )

        return obj

    def get_success_url(self):
        cart_pk=self.request.session['cart_pk']
        del(self.request.session['cart_pk'])
        if self.request.user.is_anonymous:
            user='Гость'
        else:
            user=self.request.user
        print(user)
       
        #получаю список книг корзине исходя из ид корзины
        booksincart = BookInCart.objects.all().filter(cart = cart_pk)
        print("books",booksincart.all())
        for book in booksincart:
            print("book: ",book.books.pk)
            cur_book=Books.objects.filter(pk=book.books.pk).last()
            print("Всего книг",cur_book.count_book)
            print("Книг в заказе",book.qantity)

            new_count=int(cur_book.count_book)- int(book.qantity)
            cur_book.count_book=new_count
            print("cur_book qantity past update",cur_book.count_book)
            cur_book.save()
            #проверю, если книг остаётся 0 - перевочу книгу(и) в неактивные
            if cur_book.count_book == 0:
                cur_book.availability=False
                cur_book.save()

        
        cdt=datetime.now()
        cdt=datetime.strftime(cdt,'%d.%m.%Y, %H:%M')
        cur_order=self.object.pk
        order=Order.objects.get(pk=cur_order)
        print(order.comment)
        comment=str(cdt)+' '+str(user)+':\n'+str(order.comment)
        order=Order.objects.filter(pk=cur_order).update(comment=comment)
        if user=='Гость':
            return reverse_lazy('home_page')
        else:
            return reverse_lazy('CRUDL_profiles:detail', kwargs={'pk':user.prof_user.pk})

    def get_success_message(self, cleaned_data):
        return f"{self.object}  - оформлен. Ожидайте звонка нашего специалиста."

class OrderUpdate(LoginRequiredMixin,UpdateView):
    model=Order
    template_name='order/o_update.html'
    fields=('contact_phone','status','comment',)

    def get_object(self, queryset=None):
        obj=super().get_object(queryset=queryset)
        global cur_comment
        cur_comment=obj.comment
        # order=Order.objects.get(pk=cur_order)
        # print('get_obj_comen',order.comment)
        return obj

    def get_success_url(self):

        #пример нотификации если заказ офоромлен
        # notify_managers(self.request.user, self.object)
        cdt=datetime.now()
        cdt=datetime.strftime(cdt,'%d.%m.%Y, %H:%M')
        user=self.request.user
        cur_order=self.object.pk
        order=Order.objects.get(pk=cur_order)
        print(order.comment)
        comment=cur_comment+'\n'+str(cdt)+' '+str(user)+':\n'+str(order.comment)
        if order.status==True:
            print('order.status==True / Canseled order')
            order=Order.objects.filter(pk=cur_order).update(status2='Отменен',comment={self.request.user:cdt})
        order=Order.objects.filter(pk=cur_order).update(comment=comment)
        prof_user=Profile.objects.get(username=user)
        return reverse_lazy("CRUDL_profiles:detail", kwargs={'pk':prof_user.pk})

src/s_admin/templates/s_admin/order/o_delete.html
{% extends "sadmin.html" %}
  {% block title %}<title>Удалить жанра {{object.name}} ???</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_cart %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 's-admin:cart' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
                    Cart
                  </a>
                </li>
              {% endblock nav_cart %}
    {% block main %}
<body>
        <h1>Удалить {{object.name}} ?</h1>
            <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Точно???"><br>
</body>
{% endblock main %}
</html>

src/s_admin/templates/s_admin/order/o_list.html
{% extends "sadmin.html" %}
{% block title %} <title>Лист всех издательств</title> {% endblock title %}

{% load crispy_forms_tags %}
{%load my_tags %}
              {% block nav_orders %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 's-admin:order' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                    Orders
                  </a>
                </li>
              {% endblock nav_orders %}

    {% block main %}
        <table class="table table-striped" width="100%" > 
            <thead class="thead-dark"></thead>
                <tr>
                    <th>Статус</th><th>Заказ</th><th>Автор заказа</th><th>Адрес доставки</th><th>Телефон</th><th>Создан</th><th>Обновлено</th><th>К оплате</th>
                </tr>
            </thead>
            {% for order in object_list %}
                <tr>

                    {% if order.status2 == 'Доставка' %}
                    <td ><a  class="btn btn-info" href="{% url 's-admin:order_update' order.pk %}">{{order.status2}}</a></td>
                    {% elif order.status2 == 'В обработке' %}
                    <td><a class="btn btn-primary" href="{% url 's-admin:order_update' order.pk %}">{{order.status2}}</td>
                    {% elif order.status2 == 'Отменен' %}
                    <td><a class="btn btn-danger" href="{% url 's-admin:order_update' order.pk %}">{{order.status2}}</td>
                    {% elif order.status2 == 'Выполнен' %}
                    <td><a class="btn btn-success" href="{% url 's-admin:order_update' order.pk %}">{{order.status2}}</td>
                    {% endif %} 


                    <td><a href="{% url 's-admin:order_update' order.pk %}">{{order}}</a></td>
                     {% if order.cart.user.prof_user.pk %}
                        <td><a href="{% url 's-admin:detail' order.cart.user.prof_user.pk %}">{{order.cart.user.prof_user.username}}</a> </td> 
                    {% else %}
                        <td>Гость </td> 
                    {% endif %}
                    
                    <td>{{order.delivery_address}}</td> 
                    <td>{{order.contact_phone}}</td>
                    <td>{{order.create}}</td>   
                    <td>{{order.update}}</td>
                    <td><a class="btn btn-outline-info" href="{% url 's-admin:cart_detail' order.cart.pk %}">{{order.cart.totalprice}} р.</a></td>           
                    <td> 
                    {% for books in order.publisher_books.all %}
                        <a href="{% url 's-admin:books_detail' books.pk %}">{{books}}</a> <br>
                    {%endfor%}
                </tr>
        {% endfor %} 
        </table>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% endblock main %}
</body>
</html>

src/s_admin/templates/s_admin/order/o_update.html
{% extends "sadmin.html" %}
  {% block title %}<title>Изменение {{object}}</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_orders %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 's-admin:order' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"></path><polyline points="13 2 13 9 20 9"></polyline></svg>
                    Orders
                  </a>
                </li>
              {% endblock nav_orders %}
    {% block main %}
       <div class=container>
     <h3>Информация о заказе</h3>
     <form action="" method="post" enctype="multipart/form-data">
        <label>Заказчик</label>
        <input type="text" value="{{object.cart.user}}" maxlength="15" class="textinput textInput form-control" disabled>
        <label>Сумма заказа</label>
        <input type="text" value="{{object.cart.totalprice}}" maxlength="15" class="textinput textInput form-control" disabled>
        <label>Книги в заказе</label>
        {% for books_q in object.cart.books.all %}
        <input type="text" value="{{books_q.books}}, Кол-во: {{books_q.qantity}}, Цена за штуку: {{books_q.price}}" maxlength="15" class="textinput textInput form-control" disabled>           
   

        {% endfor %}
        {% csrf_token %}
            {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Обновить">
    <a class="btn btn-success" href="{% url 's-admin:order'%}">Back </a>
     </form>
    </div>

</body>
{% endblock main %}
</html>