src/cart/urls.py
from django.urls import path
app_name="cart"
from . import views

urlpatterns = [
    path('add/', views.AddBookToCart.as_view(),name='add'),
    path('mycart/', views.CartDetail.as_view(),name='my'),
    path('delete/<int:pk>', views.BookInCartDelete.as_view(),name='delete'),

]

src/proj/urls.py
from django.contrib import admin
from django.urls import path , include
from test_hello_word.views import test_form,test_pk,test_created,test,Test_B_V,Genre_Create,Genre_Update,Genre_List,Genre_Delete,Genre_DetaleView
from books.views import BooksCreate,BooksDetail,BooksUpdate,BooksDelete,BooksList
from home_page.views import Home_page
from django.conf import settings
from django.conf.urls.static import static
from books.auth_view import Mylogin,Mylogout,MyPasswordChange
from profiles import urls
from order import urls
from cart import urls
# from phones import 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Home_page.as_view(),name='home_page'),
    path('catalogs/',include('test_hello_word.urls', namespace="CRUD_genre")),
    path('books/',include('books.urls', namespace="CRUDL_books")),
    path('login/',Mylogin.as_view(), name='login'),
    path('logout/',Mylogout.as_view(), name='logout'),
    path('change-password/',MyPasswordChange.as_view(), name='change-password'),
    path('profiles/',include('profiles.urls', namespace="CRUDL_profiles")),
    path('cart/',include('cart.urls', namespace="cart")),
    path('s-admin/',include('s_admin.urls', namespace="s-admin")),
    path('order/',include('order.urls', namespace="order"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#конструкция +static  специально для режими разработке, в проде эту строку нужно удалить

src/s_admin/urls.py
from django.urls import path
app_name="s-admin"
from . import views

urlpatterns = [
    path('', views.S_Admin.as_view(),name='index'),
    path('customers', views.CustomersList.as_view(),name='customers'),
    path('customers/update/<int:pk>', views.CustomersUpdate.as_view(),name='update'),
    path('customers/detail/<int:pk>', views.CustomersDetail.as_view(),name='detail'),

    path('books', views.SAdminBooksList.as_view(),name='books'),
    path('books/create', views.SAdminBooksCreate.as_view(),name='books_create'),
    path('books/update/<int:pk>', views.SAdminBooksUpdate.as_view(),name='books_update'),
    path('books/detail/<int:pk>', views.SAdminBooksDetail.as_view(),name='books_detail'),
    path('books/delete/<int:pk>', views.SAdminBooksDelete.as_view(),name='books_delete'),

    path('genre', views.SAdminGenreList.as_view(),name='genre'),
    path('genre/create', views.SAdminGenreCreate.as_view(),name='genre_create'),
    path('genre/update/<int:pk>', views.SAdminGenreUpdate.as_view(),name='genre_update'),
    path('genre/detail/<int:pk>', views.SAdminGenreDetail.as_view(),name='genre_detail'),
    path('genre/delete/<int:pk>', views.SAdminGenreDelete.as_view(),name='genre_delete'),
    
    path('author', views.SAdminAuthorList.as_view(),name='author'),
    path('author/create', views.SAdminAuthorCreate.as_view(),name='author_create'),
    path('author/update/<int:pk>', views.SAdminAuthorUpdate.as_view(),name='author_update'),
    path('author/detail/<int:pk>', views.SAdminAuthorDetail.as_view(),name='author_detail'),
    path('author/delete/<int:pk>', views.SAdminAuthorDelete.as_view(),name='author_delete'),

    path('cart', views.SAdminCartList.as_view(),name='cart'),
    path('cart/update/<int:pk>', views.SAdminCartUpdate.as_view(),name='cart_update'),
    path('cart/detail/<int:pk>', views.SAdminCartDetail.as_view(),name='cart_detail'),
    path('cart/delete/<int:pk>', views.SAdminCartDelete.as_view(),name='cart_delete'),

    path('publisher', views.SAdminPublisherList.as_view(),name='publisher'),
    path('publisher/create', views.SAdminPublisherCreate.as_view(),name='publisher_create'),
    path('publisher/update/<int:pk>', views.SAdminPublisherUpdate.as_view(),name='publisher_update'),
    path('publisher/delete/<int:pk>', views.SAdminPublisherDelete.as_view(),name='publisher_delete'),

    path('series', views.SAdminSeriesList.as_view(),name='series'),
    path('series/create', views.SAdminSeriesCreate.as_view(),name='series_create'),
    path('series/update/<int:pk>', views.SAdminSeriesUpdate.as_view(),name='series_update'),
    path('series/delete/<int:pk>', views.SAdminSeriesDelete.as_view(),name='series_delete'),

    path('order', views.SAdminOrderList.as_view(),name='order'),
    #доделать
    # path('order/detail/<int:pk>', views.SAdminCartDetail.as_view(),name='order_detail'),
    path('order/update/<int:pk>', views.SAdminOrderUpdate.as_view(),name='order_update'),
    path('order/delete/<int:pk>', views.SAdminSeriesDelete.as_view(),name='orders_delete'),
]

src/s_admin/views.py
from django.shortcuts import render
#cart
from cart.models import BookInCart,Cart
#books
from books import models as books_model 
from books import views as book_view

#cart

from cart import models as cart_model

#order
from order.models import Order

#profile
from profiles.views import ProfilesDetail,ProfilesUpdate,ProfilesList
from profiles.models import Profile
from profiles.forms import CreateProfileFormModel
from django.contrib.auth.models import User

from django.core.exceptions import PermissionDenied
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView,DetailView,UpdateView,DeleteView,ListView,FormView,TemplateView
from django.contrib.auth.mixins import PermissionRequiredMixin
from datetime import datetime

# Create your views here.

#
# ДОДЕЛАТЬ ПРОВЕРКУ НА ПРОФИЛЬ, ТО ЧТО СЕЙЧАС - НЕ РАБОТАЕТ

class SAdminOrderList(LoginRequiredMixin,ListView):
    model=Order
    template_name='s_admin/order/o_list.html'

    def get_queryset(self,*args,**kwargs):
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminOrderUpdate(LoginRequiredMixin,UpdateView):
    model=Order
    template_name='s_admin/order/o_update.html'
    fields=('status2','delivery_address','contact_phone','comment')

    def get_object(self, queryset=None):
        obj=super().get_object(queryset=queryset)
        global cur_comment
        cur_comment=obj.comment
        # order=Order.objects.get(pk=cur_order)
        # print('get_obj_comen',order.comment)
        return obj

    def get_success_url(self):
        user=self.request.user
        cdt=datetime.now()
        cdt=datetime.strftime(cdt,'%d.%m.%Y, %H:%M')
        cur_order=self.object.pk
        order=Order.objects.get(pk=cur_order)
        print(order.comment)
        comment=cur_comment+'\n'+str(cdt)+' '+str(user)+':\n'+str(order.comment)
        order=Order.objects.filter(pk=cur_order).update(comment=comment)

        return reverse_lazy('s-admin:order')

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class S_Admin(LoginRequiredMixin,ListView):
    model=Order
    template_name='s_admin/index.html'
    context_object_name = "orders"

    def get_context_data(self,**kwargs):
        i=0
        j=0
        b=0
        k=0
        context = super().get_context_data(**kwargs)
        orders=Order.objects.all()
        for order in orders:
            if order.status2=='Отменен':
                i+=1
                context['canseled']=i
            if order.status2=='Доставка':
                j+=1
                context['delivery']=j
            if order.status2=='В обработке':
                b+=1
                context['inprog']=b
            if order.status2=='Выполнен':
                k+=1
                context['success']=k
      
        return context

    def render_to_response(self, context, **response_kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            raise PermissionDenied
        return super().render_to_response(context, **response_kwargs)    



class CustomersList(ProfilesList):
    template_name='s_admin/customers/list.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class CustomersUpdate(ProfilesUpdate):
    template_name='s_admin/customers/update.html'
    def get_success_url(self):
        return reverse_lazy('s-admin:customers')

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class CustomersDetail(ProfilesDetail):
    template_name='s_admin/customers/detail.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

#product|books CRUDL for S-Admin portal
class SAdminBooksList(LoginRequiredMixin,book_view.BooksList):
    template_name='s_admin/books/b_list.html'
    paginate_by=None
    paginate_by=4
    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminBooksDetail(LoginRequiredMixin,book_view.BooksDetail):
    template_name='s_admin/books/b_detail.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminBooksDelete(book_view.BooksDelete):
    template_name='s_admin/books/b_delete.html'
    success_url =reverse_lazy('s-admin:books')

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminBooksUpdate(book_view.BooksUpdate):
    template_name='s_admin/books/b_update.html'
    def get_success_url(self):
        return reverse_lazy('s-admin:books_detail', kwargs={'pk':self.object.pk})

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminBooksCreate(book_view.BooksCreate):
    template_name='s_admin/books/b_create.html'
    def get_success_url(self):
        return reverse_lazy('s-admin:books_detail', kwargs={'pk':self.object.pk})

    def get_context_data(self, **kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return super().get_context_data(**kwargs)

#genre CRUD
class SAdminGenreCreate(LoginRequiredMixin,CreateView):
    model=books_model.Genre
    fields=('__all__')
    template_name='s_admin/genre/g_create.html'
    success_url =reverse_lazy('s-admin:genre')

    def get_context_data(self, **kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return super().get_context_data(**kwargs)


class SAdminGenreList(LoginRequiredMixin,ListView):
    model=books_model.Genre
    template_name='s_admin/genre/g_list.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminGenreUpdate(LoginRequiredMixin,UpdateView):
    model=books_model.Genre
    fields=('__all__')
    template_name='s_admin/genre/g_update.html'
    def get_success_url(self):
        return reverse_lazy('s-admin:genre_detail', kwargs={'pk':self.object.pk})

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 
class SAdminGenreDetail(LoginRequiredMixin,DetailView):
    model=books_model.Genre
    template_name='s_admin/genre/g_detail.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

class SAdminGenreDelete(LoginRequiredMixin,DeleteView):
    model=books_model.Genre
    template_name='s_admin/genre/g_delete.html'
    success_url =reverse_lazy('s-admin:genre')

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return self.model.objects.all() 

#author CRUD
class SAdminAuthorCreate(LoginRequiredMixin,CreateView):
    model=books_model.Author
    fields=('__all__')
    template_name='s_admin/author/a_create.html'
    success_url =reverse_lazy('s-admin:author')

    def get_context_data(self, **kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:
            return super().get_context_data(**kwargs)


class SAdminAuthorList(LoginRequiredMixin,ListView):
    model=books_model.Author
    template_name='s_admin/author/a_list.html'

    def get_queryset(self,*args,**kwargs):
        print(self.request.user.groups.get())
        if self.request.user.groups.filter(name='Customers'):
            return self.handle_no_permission()
        else:

src/s_admin/templates/s_admin/author/a_create.html
{% extends "sadmin.html" %}
  {% block title %}<title>Добавление новой книги</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_author %}
                <li class="nav-item d-flex justify-content-between">
                  <a class="nav-link active" href="{% url 's-admin:author' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Author
                  </a>
              {% endblock nav_author %}
    {% block main %}

     <div class=container>
     <h3>Добавление новой книги пользователем  {{user}}</h3>
     <form  action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Создать">
    <a class="btn btn-success" href="{% url 's-admin:author'%}">Back </a>
    </form>
    </div>
    {% endblock main %}
</body>
</html>

src/s_admin/templates/s_admin/author/a_delete.html
{% extends "sadmin.html" %}
  {% block title %}<title>Удалить жанра {{object.name}} ???</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_author %}
                <li class="nav-item d-flex justify-content-between">
                  <a class="nav-link active" href="{% url 's-admin:author' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Author
                  </a>
              {% endblock nav_author %}
    {% block main %}
<body>
        <h1>Удалить {{object.name}} ?</h1>
            <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="Точно???"><br>
</body>
{% endblock main %}
</html>

src/s_admin/templates/s_admin/author/a_detail.html
{% extends "sadmin.html" %}
  {% block title %}<title>Детальный обзор Книги {{object.name}}</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_author %}
                <li class="nav-item d-flex justify-content-between">
                  <a class="nav-link active" href="{% url 's-admin:author' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Author
                  </a>
              {% endblock nav_author %}
    {% block main %}
<body>
    <h1>Информация об авторе: {{object.name}}</h1>

<div class="card mb-10" style="max-width: 1850px;">
  <div class="row no-gutters">
    <div class="col-md-5">
      <div class="card-body">
            <ul class="list-group list-group-flush">

                <li class="list-group-item">Имя автора: <b>{{object.first_name}}</b></li>
                <li class="list-group-item">Фамилия автора: <b>{{object.last_name}}</b></li>
                <li class="list-group-item">Информация об авторе: <br><b>{{object.description}}</b></li>

            </ul>
      </div>
    </div>
  </div>
</div>
        <a class="btn btn-success" href="{% url 's-admin:author'%}">Back </a>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
{% endblock main %}
</html>

src/s_admin/templates/s_admin/author/a_list.html
{% extends "sadmin.html" %}
{% block title %} <title>Лист всех жанров</title> {% endblock title %}

{% load crispy_forms_tags %}
              {% block nav_author %}
                <li class="nav-item d-flex justify-content-between">
                  <a class="nav-link active" href="{% url 's-admin:author' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Author
                  </a>
              {% endblock nav_author %}
    {% block main %}

        <table class="table table-striped" width="100%" > 
            <thead class="thead-dark"></thead>
                <tr>
                    <th>#</th><th>Имя автора</th><th>Фамилия автора</th><th>Книги данного автора</th><th>#</th>
                </tr>
            </thead>
            {% for author in object_list %}
                <tr>
                  <td><a href="{% url 's-admin:author_update' author.pk %}"><svg class="bi bi-pencil-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                  </svg></a></td>
                  <td><a href="{% url 's-admin:author_detail' author.pk %}">{{author.first_name}}</a> </td>     
                  <td>{{author.last_name}}</td>
                  <td>   
                            {% for books in author.books_author.all %}
                                <a href="{% url 'CRUDL_books:detail' books.pk %}">{{books}}</a> <br>
                            {%endfor%}
                    </td>
                  <td><a href="{% url 's-admin:author_delete' author.pk %}"><svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                  </svg></a></td>
                </tr>
        {% endfor %} 
        </table>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% endblock main %}
</body>
</html>

src/s_admin/templates/s_admin/author/a_update.html
{% extends "sadmin.html" %}
  {% block title %}<title>Изменение жанра {{object.name}}</title>{% endblock title %}
{% load crispy_forms_tags %}
              {% block nav_author %}
                <li class="nav-item d-flex justify-content-between">
                  <a class="nav-link active" href="{% url 's-admin:author' %}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
                    Author
                  </a>
              {% endblock nav_author %}
    {% block main %}
       <div class=container>
     <h3>Обновление данных для {{object.name}}</h3>
     <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Обновить">
    <a class="btn btn-success" href="{% url 's-admin:genre'%}">Back </a>
     </form>
    </div>

</body>
{% endblock main %}
</html>